version: "3.8"

services:
  php:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
