version: "3.8"

services:
  php-fpm:
    build:
      context: .
    container_name: php-fpm
    volumes:
      - ./:/var/www/html'
    working_dir: /var/www/html
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
